---
- name: configure tomcat9 and tomcat9-admin
  hosts: all
  tasks:
   - name: configure tomcat9 and tomcat9-admin
     include: "{{item}}"
     with_items:
        - install_tomcat.yml
        - copy_tomcat.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml
        - check_tomcat_response.yml
...
