---
- name: configuring apache2
  hosts: all
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: edit the index.html file
      copy:
        content: "Roronova zoro"
        dest: /var/www/html/index.html
    - name: restart apache2
      service:
         name: apache2
         state: restarted
    - name: check tomat response on server1
      uri:
        url: http://172.31.92.119
        status_code: 200
    - name: check tomcat response on server2
      uri:
         url: http://172.31.85.46
         status_code: 200
...
 
