---
- name: Install s/w's of using play scope variables
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: install/Uninstall
      apt:
         name: "{{a}}"
         state: "{{b}}"
         update_cache: "{{c}}"
...
